# Generated by Django 4.1.5 on 2023-02-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_product_tags_customer_date_created_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Product',
            new_name='product',
        ),
    ]
