# Generated by Django 4.1.5 on 2023-02-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
