# Generated by Django 4.1.5 on 2023-02-07 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_alter_customer_images_alter_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='images',
            new_name='profile',
        ),
    ]
