# Generated by Django 4.1.5 on 2023-02-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_rename_images_customer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='forget_password_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
