# Generated by Django 4.1.5 on 2023-02-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0008_customer_forget_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
